### ISSUE TITLE
Leetcode Daily Problem 13 October 2022

### ISSUE THREAD

**Issue by Jatin-parmar** [kavania2002/dailyProblems#6]
Wants to add Leetcode Daily Problem 13 October 2022

**Comment by kavania2002** [comment]
Dear @Jatin-parmar , you can work on this.

**Comment by isaacmtp** [comment]
can you please assign this to me

**Comment by kavania2002** [comment]
@isaacmtp please try another problem.
It was already being assigned.

**Comment by issac5693** [comment]
Ok
